// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace performance_test.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260310052156_added Auditor servvices")]
    partial class addedAuditorservvices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuditNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NodeKind")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("AuditNodes");
                });

            modelBuilder.Entity("AuditorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuditNodeId")
                        .HasColumnType("int");

                    b.Property<string>("Contact")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Dept")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EmpId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AuditNodeId")
                        .IsUnique();

                    b.ToTable("AuditorProfiles");
                });

            modelBuilder.Entity("AuditorProfileAuditorServices", b =>
                {
                    b.Property<int>("AuditorProfilesId")
                        .HasColumnType("int");

                    b.Property<int>("AuditorServicesId")
                        .HasColumnType("int");

                    b.HasKey("AuditorProfilesId", "AuditorServicesId");

                    b.HasIndex("AuditorServicesId");

                    b.ToTable("AuditorProfileAuditorServices");
                });

            modelBuilder.Entity("performance_test.models.AuditNodeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuditNodeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AuditNodeId")
                        .IsUnique();

                    b.ToTable("AuditNodeData");
                });

            modelBuilder.Entity("performance_test.models.AuditorServices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditorServices");
                });

            modelBuilder.Entity("AuditNode", b =>
                {
                    b.HasOne("AuditNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AuditorProfile", b =>
                {
                    b.HasOne("AuditNode", "AuditNode")
                        .WithOne("Auditor")
                        .HasForeignKey("AuditorProfile", "AuditNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditNode");
                });

            modelBuilder.Entity("AuditorProfileAuditorServices", b =>
                {
                    b.HasOne("AuditorProfile", null)
                        .WithMany()
                        .HasForeignKey("AuditorProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("performance_test.models.AuditorServices", null)
                        .WithMany()
                        .HasForeignKey("AuditorServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("performance_test.models.AuditNodeData", b =>
                {
                    b.HasOne("AuditNode", "AuditNode")
                        .WithOne("Data")
                        .HasForeignKey("performance_test.models.AuditNodeData", "AuditNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditNode");
                });

            modelBuilder.Entity("AuditNode", b =>
                {
                    b.Navigation("Auditor");

                    b.Navigation("Children");

                    b.Navigation("Data")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
